# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

matrix:
  include:
    - os: windows
      language: sh
      before_install:
        - choco install julia
        - julia --color=yes -e 'using InteractiveUtils; versioninfo(verbose=true)'
      script:
        - julia --color=yes --project=. -e 'using Pkg; Pkg.test()'

before_script:
  - julia --color=yes -e 'using Pkg; pkg"dev https://github.com/wookay/Jive.jl.git"'
  - julia --color=yes -e 'using Pkg; pkg"precompile"'
