# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

matrix:
  include:
    - os: linux
      language: julia
      julia:
        - 1.0

    - os: windows
      language: sh
      cache:
        directories:
          - $HOME/.julia
      before_install:
          - choco install julia
          - tail -1000 /c/ProgramData/chocolatey/logs/chocolatey.log
          - set TERM=xterm-256color
          - julia --color=yes -e 'using InteractiveUtils; versioninfo(verbose=true)'
      script:
        - julia --color=yes -e 'using Pkg; pkg"dev ."; pkg"test TestOcto"'

before_script:
  - julia --color=yes -e 'using Pkg; pkg"add https://github.com/wookay/Jive.jl.git"'
