# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

matrix:
  include:
    - os: windows
      language: sh
      before_install:
        - choco install julia
      script:
        - julia --color=yes --project=. -e 'using Pkg; Pkg.test()'

before_script:
  - julia --color=yes -e 'using Pkg; Pkg.develop(PackageSpec(url="https://github.com/wookay/Jive.jl.git", version=v"0.1.0"))
