# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

matrix:
  include:
    - os: windows
      language: sh
      before_install:
        - choco install julia
      script:
        - julia --color=yes -e 'using Pkg; pkg"dev ."'
        - julia --color=yes -e 'using Pkg; Pkg.test("TestOcto")'

before_script:
  - julia --color=yes -e 'using Pkg; pkg"add https://github.com/wookay/Jive.jl.git"'
