# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
services:
  - postgresql
julia:
  - 1.0
  - nightly
matrix:
  include:
  - name: "linux"
    os: linux
    env: POSTGRESQL_VERSION=9.6 PGHOST="/var/run/postgresql"
  - name: "osx"
    os: osx
before_install:
  - sudo service postgresql stop && sudo service postgresql start $POSTGRESQL_VERSION
  - psql -U postgres -tc 'SHOW server_version'
  - psql -U postgres -c '\conninfo'
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
