## Documentation: http://docs.travis-ci.com/user/languages/julia/

notifications:
  email: false

language: julia

os:
  - linux

julia:
  - 1.5

services:
  - mysql

cache:
  directories:
  - $HOME/.julia/artifacts

before_script:
  # linux - MySQL      - 5.6.33
  - if [[ "$TRAVIS_OS_NAME" == linux ]]; then mysql -e 'show variables like "socket";' -uroot                                              ; fi

  # MySQL
  - mysql -e 'CREATE DATABASE IF NOT EXISTS mysqltest;' -uroot
  - mysql -e 'GRANT ALL PRIVILEGES ON mysqltest.* TO "root"@"localhost"' -uroot
  - mysql --version

script:
  - julia -e 'using Pkg; pkg"dev MySQL Octo Jive"'
  - cd test && julia runtests.jl
