# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

matrix:
  include:
    - os: linux
      language: julia
      julia:
        - 1.0

    - os: windows
      language: sh
      cache:
        directories:
          - $HOME/.julia
      before_install:
          - choco install julia
          - tail -50 /c/ProgramData/chocolatey/logs/chocolatey.log
          - echo -e "Default \e[39mDefault"
          - echo -e "Default \e[30mBlack"
          - echo -e "Default \e[31mRed"
          - echo -e "Default \e[32mGreen"
          - echo -e "Default \e[33mYellow"
          - echo -e "Default \e[34mBlue"
          - echo -e "Default \e[35mMagenta"
          - echo -e "Default \e[36mCyan"
          - echo -e "Default \e[37mLight gray"
          - echo -e "Default \e[90mDark gray"
          - echo -e "Default \e[91mLight red"
          - echo -e "Default \e[92mLight green"
          - echo -e "Default \e[93mLight yellow"
          - echo -e "Default \e[94mLight blue"
          - echo -e "Default \e[95mLight magenta"
          - echo -e "Default \e[96mLight cyan"
          - echo -e "Default \e[97mWhite"
          - julia --color=yes -e 'using InteractiveUtils; versioninfo(verbose=true)'
      script:
        - julia --color=yes -e 'using Pkg; pkg"dev ."; pkg"test TestOcto"'

before_script:
  - julia --color=yes -e 'using Pkg; pkg"add https://github.com/wookay/Jive.jl.git"'
